import Navbar from "@/components/navbar";
import "./globals.css";
import { Inter } from "next/font/google";
import AboutFooter from "@/components/about/footer";
import { Providers } from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <Providers>
          <Navbar />
          {children}
          <AboutFooter />
        </Providers>
      </body>
    </html>
  );
}
