import './globals.css';

import { Providers } from './providers';

import Navbar from '@/components/navbar';
import AboutFooter from '@/components/about/footer';

import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <Providers>
          <Navbar />
          {children}
          <AboutFooter />
        </Providers>
      </body>
    </html>
  );
}
